- hosts: jenkins
  remote_user: root
  tasks:
  - name: Update to the latest packages
    yum:
      name: '*'
      state: latest

  - name: Add Apache and Git
    yum: pkg={{item}} state=latest
    with_items:
     - httpd
     - git
     - mod_proxy_html

  - name: Add Jenkins repository
    get_url:
      url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
      mode: 0644

  - name: Add Jenkins repo key  
    rpm_key:
      state: present 
      key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

  - name: Fix SELinux context on repo file
    file:
      path: /etc/yum.repos.d/jenkins.repo
      seuser: unconfined_u
      serole: object_r 
      setype: system_conf_t
      selevel: s0

#  Only available in Ansible 2.1
#  - name: Add Jenkins repository
#    yumrepo:
#      name: jenkins_repo
#      description: Add Jenkins YUM repo
#      file: jenkins.repo
#      baseurl: http://pkg.jenkins-ci.org/redhat-stable/
#      enabled: yes
#      gpgcheck: no

  - name: Install OpenJDK
    yum:
      name: java-1.7.0-openjdk
      state: present

  - name: Install Jenkins
    yum:
      name: jenkins
      state: present

#  - name: Configure firewalld port 8080/tcp
#    firewalld:
#      zone: public
#      port: 8080/tcp
#      permanent: true
#      immediate:

#  - name: Configure firwalld http service
#    firewalld:
#      zone: public
#      service: http
#      permanent: true
#      immediate:

  - name: Disable Jenkins HTTP listener
    replace:
      dest=/etc/sysconfig/jenkins
      regexp='JENKINS_PORT="8080"'
      replace='JENKINS_PORT="-1"'
    notify:
      - restart jenkins

  - name: Enable MD5 in Java security (work around for current bug)
    replace:
      dest=/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.95-2.6.4.0.el7_2.x86_64/jre/lib/security/java.security
      regexp='jdk.certpath.disabledAlgorithms=MD2, MD5, RSA keySize < 1024'
      replace='jdk.certpath.disabledAlgorithms=MD2, RSA keySize < 1024'
    notify:
      - restart jenkins

  - name: Limit AJP listener to localhost 
    replace:
      dest=/etc/sysconfig/jenkins
      regexp='JENKINS_AJP_LISTEN_ADDRESS=""'
      replace='JENKINS_AJP_LISTEN_ADDRESS="127.0.0.1"'
    notify:
      - restart jenkins

# Being exploded by Jenkins but not seen in plugins
#  - name: Add the Google OAuth plugin
#    get_url:
#      url: http://updates.jenkins-ci.org/latest/google-oauth-plugin.hpi
#      dest: /var/lib/jenkins/plugins
#    notify:
#      - restart jenkins

  - name: Enable and start Apache
    service:
      name: httpd
      enabled: yes
      state: started

# Need
# Configure SSL Proxy

  - name: Enable and start Jenkins
    service:
      name: jenkins
      enabled: yes
      state: started

  - name: Deploy jenkins proxy template
    template:
      src: apache_ajp_proxy
      dest: /etc/httpd/conf.d/jenkins.conf
      owner: root
      group: root
      mode: 0644
    notify:
      - restart apache

# Need
# Google app auth (http://stackoverflow.com/questions/17676232/how-to-configure-jenkins-authentication-with-google-apps)

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted

    - name: restart jenkins
      service:
        name: jenkins
        state: restarted
