---
- hosts: localhost
  tasks:

  - name: Pull in the swap variables
    include_vars: digital_ocean.env


  - name: Create Droplet
    digital_ocean:
      state: present
      command: droplet
      name: mydroplettest
      api_token: "{{DO_API_KEY}}"
      size_id: 512mb
      region_id: nyc2
      image_id: centos-7.1-x64
      wait_timeout: 500
    register: my_droplet
  
  - debug: msg="ID is {{ my_droplet.droplet.id }}"

  - debug: msg="IP is {{ my_droplet.droplet.ip_address }}"
